dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chianlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chianlink-brownie-contracts@1.1.1'